### ISSUE TITLE
ImportError: cannot import name 'MINIO_BUCKET'

### ISSUE THREAD

**Issue by mrcrilly** [singularityhub/sregistry#305]
**Describe the bug**
I'm installing `sregistry` via the "official"(?) Ansible Role: https://github.com/grycap/ansible-role-singularity-registry. The only changes I've made to it is to customise the Nginx container with a custom configuration to include my TLS certificates as they're rotated. I've included this code below:

```
- block:
    - name: Upload Nginx HTTPS config
      template:
          src: nginx-https.conf
          dest: "{{ sregistry_dir }}/nginx.conf"

    - name: Upload registry certificate
      copy:
          src: "{{ nginx_https_certificate }}"
          dest: "{{ sregistry_dir }}/registry.crt"

    - name: Upload registry key
      copy:
          src: "{{ nginx_https_key }}"
          dest: "{{ sregistry_dir }}/registry.key"
  when: nginx_use_https
```

From a freshly cloned copy of the `sregistry` repository, using the `master` branch (the default for the Role above), I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 128, in handle_uncaught_exception
    callback, param_dict = resolver.resolve_error_handler(500)
  File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 597, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./shub/urls.py", line 19, in <module>
    from shub.apps.library import urls as library_urls
  File "./shub/apps/library/urls.py", line 12, in <module>
    from shub.apps.library import views
  File "./shub/apps/library/views/__init__.py", line 2, in <module>
    from .images import (
  File "./shub/apps/library/views/images.py", line 19, in <module>
    from shub.settings import (
ImportError: cannot import name 'MINIO_BUCKET'
```

This has only started happening in the week or so. I believe I was able to successfully run `sregistry` about two weeks ago. I notice that some of the latest commits to the `master` branch contain references to `minio` so perhaps something has been introduced that's breaking this?

**To Reproduce**
The steps to reproduce are either:
1. Execute the above Ansible Role
1. See this file for manual steps: https://github.com/grycap/ansible-role-singularity-registry/blob/master/tasks/sregistry.yml

**Expected behavior**
A working Singularity Registry installation with my TLS certificate in place listening on `443`.

If applicable, add versions and screenshots to help explain your problem.
* Latest `master` branch
* Ansible 2.9.9

Docker information:

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:13:48 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:12:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by vsoch** [comment]
You’ll want to use an earlier version (before Minio was added) to use the ansible recipe - it isn’t “officially supported” but was contributed, so let me see if I can ping the contributor to make a version for Minio.

**Comment by mrcrilly** [comment]
Thanks @vsoch. I've confirmed commit `dd0600d1dd6550c68127594b4bac19b84e3e69ba` works fine.

**Comment by vsoch** [comment]
hey @serlophug ! Would you be able to help to update the ansible role to add the newly added Minio? I think it would just come down to adding the extra envars and container. I can also take a shot and either PR to your repo or create a recipe here. Let me know your preference! In the meantime it might also make sense to add a note in the docs to say the version of sregistry supported. Thanks!

**Comment by mrcrilly** [comment]
Can I recommend we get a new release set in Releases? The options there are quite old. Perhaps a new released based on `dd0600d1dd6550c68127594b4bac19b84e3e69ba` given I can confirm it works?

**Comment by vsoch** [comment]
Sure can do this tomorrow. I don’t release on the repo but instead via the Docker containers since most users grab a container and not the source code.

**Comment by mrcrilly** [comment]
That's probably true, BUT, the Ansible Role does pull the repository and then builds the image. It might be worth @serlophug changing it to work with a new release candidate instead of `master`.

Also can I suggest not using `master` for `[WIP]` items? :-)

And finally could you direct me to the Docker image that you manage? I might switch our deployment to just use that instead.

**Comment by vsoch** [comment]
Good suggestion! The Docker images are those referenced in the docker-compose.yml, mentioned in the setup docs, and on quay.io. https://quay.io/repository/vanessa/sregistry?tab=tags

**Comment by mrcrilly** [comment]
Thanks. And thanks for all the great work. The Department of Environment Science, Queensland, Australia, says hi! :-)

**Comment by vsoch** [comment]
okay, for a quick fix I've released (on GitHub) the current master along with the last version without Minio [1.1.23](https://github.com/singularityhub/sregistry/releases/tag/v1.1.23). I'd highly suggest using the Minio backend it hugely improves memory usage and upload speed (multipart uploads!) I also added a quick fix to the docs to note the version required:

![image](https://user-images.githubusercontent.com/814322/83720624-a101a980-a5f6-11ea-901e-131790fa848f.png)

Let's wait to hear from @serlophug to decide on next steps - either updating his repo for Minio support (this would be my preference, it's a better registry) or providing a recipe here. I'm off to bed, thanks for your kind words! :)

**Comment by serlophug** [comment]
Hi @mrcrilly  and @vsoch !
Sure, I also think that update my repo is the best option. @vsoch , would you give me more information about the Minio configuration for sregistry? Regarding the docker container, Do I have to modify the Dockerfile?

**Comment by vsoch** [comment]
@serlophug any updates? Do you need any help?

**Comment by mrcrilly** [comment]
@vsoch I took your `docker-compose.yml` file from here `https://github.com/singularityhub/sregistry/blob/master/docker-compose.yml` and I still get errors.

From `sregistry-master_worker_1`:

```
ImportError: cannot import name 'MINIO_BUCKET'
```

And from `sregistry-master_scheduler_1`:

```
ImportError: cannot import name 'MINIO_BUCKET'
```

Given these are using the images in your Docker Compose file I would have expected them to have worked straight up?

These two containers just constantly restart themselves.

**Comment by vsoch** [comment]
You’ll need to give me the exact steps to reproduce your error, I’ve tried several times and cannot. Remember that you’ll need to stop and remove all containers, and I’d even try removing and re pulling the images.

**Comment by vsoch** [comment]
And wasn’t this an issue with the ansible recipe? Any updates @serlophug? You can’t mix the two versions - the Minio version won’t work with ansible and the older ansible version won’t work with the current master. Based on the error I suspect you have a mismatch and it’s reporting correctly there is no MINIO_BUCKET variable because there is not.

**Comment by mrcrilly** [comment]
I'm using the following `docker-compose.yml` file (which contains Jinja2 templating that can be ignored - it's rendered correctly on the other end):

```
db:
  restart: always
  image: postgres
  volumes:
    - /db/sregistry-psql-data:/var/lib/postgresql/data
  environment:
   - POSTGRES_HOST_AUTH_METHOD=trust

uwsgi:
  restart: always
  image: quay.io/vanessa/sregistry
  environment:
    - http_proxy=<hidden>
    - https_proxy=<hidden>
    - HTTP_PROXY=<hidden>
    - HTTPS_PROXY=<hidden>
  env_file:
    - ./.minio-env
  volumes:
    - .:/code
    - ./static:/var/www/static
    - ./images:/var/www/images
  links:
    - minio
    - redis
    - db

{% if nginx_use_http %}
nginx:
  restart: always
  image: quay.io/vanessa/sregistry_nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
    - db
{% else %}
nginx:
  restart: always
  image: quay.io/vanessa/sregistry_nginx
  ports:
    - "443:443"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    - ./registry.crt:/etc/nginx/registry.crt
    - ./registry.key:/etc/nginx/registry.key
  volumes_from:
    - uwsgi
  links:
    - uwsgi
    - db
{% endif %}

redis:
  restart: always
  image: redis:latest

scheduler:
  restart: always
  image: quay.io/vanessa/sregistry
  command: python /code/manage.py rqscheduler
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
  env_file:
    - ./.minio-env
  links:
    - minio
    - redis
    - db

worker:
  restart: always
  image: quay.io/vanessa/sregistry
  command: python /code/manage.py rqworker default
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
  env_file:
    - ./.minio-env
  links:
    - minio
    - redis
    - db

minio:
  image: minio/minio
  volumes:
    - ./minio-images:/images
  env_file:
    - ./.minio-env
  ports:
    - "9000:9000"
  command: ["server", "images"]
```

This is a replacement `docker-compose.yml` file for the one that @serlophug provides in his Ansible Role. Using his Role (which hasn't been updated) combined with my custom compose file, I am simply running: `docker-compose up -d` against the `master` branch of `sregistry`. This should be enough to bring everything up, but even after cleaning out all downloaded Docker images and starting from a clean slate, I get the same error from both of the previously mentioned containers.

**Comment by vsoch** [comment]
Did you confirm that the Minio bucket is still defined in your settings/config.py? If it’s not able to import from there, that’s the core of the issue.

i’m happy to help to debug but since you are changing the standard usage and combining these two different versions with your custom code it’s slightly out of scope for that.

**Comment by vsoch** [comment]
Try starting one of the containers with a shell entry point and inspecting the code at /code and also check the file when it’s bound to your machine.

**Comment by vsoch** [comment]
@mrcrilly maybe you could help @serlophug to update his repo instead of trying to hack on it separately?

**Comment by mrcrilly** [comment]
> Did you confirm that the Minio bucket is still defined in your settings/config.py? If it’s not able to import from there, that’s the core of the issue.

I'm afraid I don't know what you mean by this. I'm not manipulating a `settings/config.py` file at all as I had no idea it existed. Can you point me towards some documentation?

> i’m happy to help to debug but since you are changing the standard usage and combining these two different versions with your custom code it’s slightly out of scope for that.

I'm doing no such thing. I'm literally cloning your code from `master` and running your `docker-compose.yml` file on a clean CentOS 7 slate - were does the "custom" code come into the picture?

> @mrcrilly maybe you could help @serlophug to update his repo instead of trying to hack on it separately?

Perhaps. I've done a lot of work to make his role work for our situation. My contract runs dry July 10th and I have other priorities, but I'll see if I can do a PR.

**Comment by vsoch** [comment]
@mrcrilly the file you want to check is under shub/settings/config.py. That's where the import of that variable is, so you'd want to see it in the file. Take a look at the file on GitHub https://github.com/singularityhub/sregistry/blob/master/shub/settings/config.py#L113

**Comment by mrcrilly** [comment]
Thank you.

So because I'm using your pre-built images, I assume I have to inject that file (via a volume) ahead of time?

**Comment by vsoch** [comment]
The docker-compose binds the present working directory to /code in the container. This is why the file in the container should be what you have updated on the host.

**Comment by mrcrilly** [comment]
OK, great! I can see it's working better now but still with an error:

```
minio.error.InvalidArgumentError: InvalidArgumentError: message: Configured region ap-southeast-2, requested us-east-1
```

Can the region not be changed in the settings?

I also understand the issue with the Ansible Role at this time. I'll try a PR, but I'm thinking I might be better producing me own public version given I don't agree with some of the architectural designs @serlophug has in his role (such as dynamically computing the `settings.py` from an Ansible variable.)

**Comment by vsoch** [comment]
All of those variables are in that same config.py settings file that I pointed out. For the ansible role, he changed it so that (most settings) you could define with the ansible recipe. The same should be done with these minio ones. For the time being, you can just update that text file and restart the containers.

**Comment by mrcrilly** [comment]
Sorry I never made my self clear.

I'm setting `MINIO_REGION` to `ap-southeast-2` and getting the above error. The error implies MinIO, or perhaps Singularity Registry, doesn't support any AWS region other than `us-east-1` - is this true?

I've `down`-ed the containers, changed it to `us-east-1` and brought them back `up` and it's working fine now.

> All of those variables are in that same config.py settings file that I pointed out. For the ansible role, he changed it so that (most settings) you could define with the ansible recipe.

Yes I consider this to be poor architecture that is fragile and breaks easily the moment the role is no longer in sync with the software it manages. It's much, much easier to understand and work with the original configuration and in fact Ansible offers features that make this easier again, so I prefer to just have the user provide a `settings.py` file that Ansible then pushes up versus complex logic to abstract a simple API behind a weaker, more complex one.

**Comment by vsoch** [comment]
I didn't develop the ansible role (but am grateful for it). I'm sorry that you are disappointed, if you'd like to contribute a more "official" ansible role to be served alongside the code base (instead of separately) I think this would be a great contribution. I'm not a regular ansible user so I would best help to follow written docs and test when something is done.

Singularity Registry should be agnostic to the region, the error message is coming from Minio. It looks a lot like this. https://github.com/minio/minio/issues/3595 I'd suggest using the mc tool that is detailed in the docs https://singularityhub.github.io/sregistry/docs/install/server#storage to see if you can debug, and if there is some config change we can do to fix it, we would want to detail that in the docs too.

**Comment by vsoch** [comment]
@mrcrilly if you want to put together the start for an ansible recipe that would copy such a settings file and open PR, I'll do the work to merge the different settings files into one, and then if you show me how to run to test I can give it a shot. If we can get a working recipe alongside the repo, that would be the goal.

**Comment by mrcrilly** [comment]
I have to revert back to `dd0600d1dd6550c68127594b4bac19b84e3e69ba` again due to using the new MinIO version failing, again.

This is as much information as I can give you:

```
$ singularity -d push -U custom_lolcow.sif library://mrcrilly/lolcontainers/lolcow.sif:latest
DEBUG   [U=1000,P=247001]  persistentPreRun()            Singularity version: 3.6.0-rc.5
DEBUG   [U=1000,P=247001]  persistentPreRun()            Parsing configuration file /usr/local/etc/singularity/singularity.conf
DEBUG   [U=1000,P=247001]  handleConfDir()               /home/michaelc/.singularity already exists. Not creating.
DEBUG   [U=1000,P=247001]  handleRemoteConf()            Ensuring file permission of 0600 on /home/michaelc/.singularity/remote.yaml
WARNING [U=1000,P=247001]  LibraryPush()                 Skipping container verifying
DEBUG   [U=1000,P=247001]  UploadImage()                 Image hash computed as 5d8064dc526ecd5b666dc6de4e04b2118b116cbf41f24bbbfda3d66523d2fdb2
DEBUG   [U=1000,P=247001]  apiGet()                      apiGet calling v1/entities/mrcrilly
DEBUG   [U=1000,P=247001]  apiGet()                      apiGet calling v1/collections/mrcrilly/lolcontainers
DEBUG   [U=1000,P=247001]  apiGet()                      apiGet calling v1/containers/mrcrilly/lolcontainers/lolcow.sif
DEBUG   [U=1000,P=247001]  apiGet()                      apiGet calling v1/images/mrcrilly/lolcontainers/lolcow.sif:sha256.5d8064dc526ecd5b666dc6de4e04b2118b116cbf41f24bbbfda3d66523d2fdb2?arch=amd64
DEBUG   [U=1000,P=247001]  postFileWrapper()             Now uploading to the library
DEBUG   [U=1000,P=247001]  postFileV2()                  Attempting to use multipart uploader
DEBUG   [U=1000,P=247001]  startMultipartUpload()        startMultipartUpload calling v2/imagefile/5/_multipart
DEBUG   [U=1000,P=247001]  apiCreate()                   apiCreate calling v2/imagefile/5/_multipart
DEBUG   [U=1000,P=247001]  postFileV2Multipart()         Multi-part upload: ID=[cd61473a-760e-4e9d-aaf4-d5a9fa9fe89f] totalParts=[1] partSize=[94867456]
DEBUG   [U=1000,P=247001]  postFileV2Multipart()         Uploading part 1 (94867456 bytes)
0.0b / 90.5MiB [------------------------------------------------------------------------------] 0 % 0.0 b/s 0s
DEBUG   [U=1000,P=247001]  multipartUploadPart()         multipartUploadPart calling v2/imagefile/5/_multipart
DEBUG   [U=1000,P=247001]  apiUpdate()                   apiUpdate calling v2/imagefile/5/_multipart
DEBUG   [U=1000,P=247001]  multipartUploadPart()         Failure uploading to presigned URL: Put "http://127.0.0.1:9000/sregistry/lolcontainers/lolcow.sif%3Asha256.5d8064dc526ecd5b666dc6de4e04b2118b116cbf41f24bbbfda3d66523d2fdb2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=newminio%2F20200705%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200705T205244Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host%3Bx-amz-content-sha256&partNumber=1&uploadId=cd61473a-760e-4e9d-aaf4-d5a9fa9fe89f&X-Amz-Signature=f62a405af05cd241c4df1d786725e42ee2daa20bb48d6345aaba3054bc08a272": dial tcp 127.0.0.1:9000: connect: connection refused
DEBUG   [U=1000,P=247001]  postFileV2Multipart()         Error uploading part 1: Put "http://127.0.0.1:9000/sregistry/lolcontainers/lolcow.sif%3Asha256.5d8064dc526ecd5b666dc6de4e04b2118b116cbf41f24bbbfda3d66523d2fdb2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=newminio%2F20200705%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200705T205244Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host%3Bx-amz-content-sha256&partNumber=1&uploadId=cd61473a-760e-4e9d-aaf4-d5a9fa9fe89f&X-Amz-Signature=f62a405af05cd241c4df1d786725e42ee2daa20bb48d6345aaba3054bc08a272": dial tcp 127.0.0.1:9000: connect: connection refused
DEBUG   [U=1000,P=247001]  abortMultipartUpload()        Aborting multipart upload ID: cd61473a-760e-4e9d-aaf4-d5a9fa9fe89f
DEBUG   [U=1000,P=247001]  abortMultipartUpload()        abortMultipartUpload calling v2/imagefile/5/_multipart_abort
DEBUG   [U=1000,P=247001]  apiUpdate()                   apiUpdate calling v2/imagefile/5/_multipart_abort
DEBUG   [U=1000,P=247001]  postFileWrapper()             Upload completed OK
0.0b / 90.5MiB [------------------------------------------------------------------------------] 0 % 0.0 b/s 0s
DEBUG   [U=1000,P=247001]  UploadImage()                 This library does not support multiple architectures per tag.
DEBUG   [U=1000,P=247001]  UploadImage()                 This tag will replace any already uploaded with the same name.
DEBUG   [U=1000,P=247001]  getTags()                     getTags calling v1/tags/1
DEBUG   [U=1000,P=247001]  setTags()                     Setting tag latest
DEBUG   [U=1000,P=247001]  setTag()                      setTag calling v1/tags/1
FATAL   [U=1000,P=247001]  func50()                      Unable to push image to library: creation did not succeed: http status code: 404
```

**Comment by vsoch** [comment]
@mrcrilly I offered ways that we could move forward to work on this together. You closed the issue. There is nothing actionable I can do with an error on your custom code that is known only to you.

**Comment by mrcrilly** [comment]
From what you understand so far, what part of the code have I customised? What gives you them impression from past communications that's customised code? If you could highlight what you believe I've cusomtised then I'd be happy to expand on the finer details around that customisation.

**Comment by vsoch** [comment]
You are deploying with ansible, are you not?

**Comment by mrcrilly** [comment]
Neither options work: not using the (unofficial, unmodified) Ansible Role nor doing it by hand following your documentation.

Starting with https://singularityhub.github.io/sregistry/docs/install/host I'm doing everything by hand. I'm working with a clean CentOS7 virtual machine (I'm aware CentOS8 is a thing.)

I am following these steps which I believe to be the most minimum of changes needed and don't constitute "custom code", but feel free to point out any errors I'm making whilst trying to complete this task...

1. Cloning the repository on the `master` branch
1. Injecting my own `config.py` which I have shared below (concealing sensitive information, of course) and instead of using `secrets.py` I place `SECRET_KEY` inside the `config.py` file...
1. Injecting my own Nginx configuration to enable TLS (which works fine), included below
1. Updating `docker-compose.yml` to volume mount the TLS certification information (file included below)
1. Executing `docker-compose up -d`
1. Logging in using GitLab
1. Creating a Collection called `lolcow`
1. Using `singularity remote add example myhost.name` to add my new Singularity Server, getting my token from the Singularity Registry token menu for my given user
1. Using `singularity remote use example` to set the remote for the next command
1. Attempting to push a `.sif` file via `singularity push -U custom_lolcow.sif library://mrcrilly/lolcow/custom_lolcow.sif:latest`

Here is the result of the last `singularity` command I execute:

```
$ singularity push -U custom_lolcow.sif library://mrcrilly/lolcow/lolcow.sif:latest
WARNING: Skipping container verifying
0.0b / 90.5MiB [------------------------------------------------------------------------------] 0 % 0.0 b/s 0s
FATAL:   Unable to push image to library: creation did not succeed: http status code: 404
```

And with debugging information:

```
$ singularity -d push -U custom_lolcow.sif library://mrcrilly/lolcow/lolcow.sif:latest
DEBUG   [U=1000,P=248639]  persistentPreRun()            Singularity version: 3.6.0-rc.5
DEBUG   [U=1000,P=248639]  persistentPreRun()            Parsing configuration file /usr/local/etc/singularity/singularity.conf
DEBUG   [U=1000,P=248639]  handleConfDir()               /home/michaelc/.singularity already exists. Not creating.
DEBUG   [U=1000,P=248639]  handleRemoteConf()            Ensuring file permission of 0600 on /home/michaelc/.singularity/remote.yaml
WARNING [U=1000,P=248639]  LibraryPush()                 Skipping container verifying
DEBUG   [U=1000,P=248639]  UploadImage()                 Image hash computed as 5d8064dc526ecd5b666dc6de4e04b2118b116cbf41f24bbbfda3d66523d2fdb2
DEBUG   [U=1000,P=248639]  apiGet()                      apiGet calling v1/entities/mrcrilly
DEBUG   [U=1000,P=248639]  apiGet()                      apiGet calling v1/collections/mrcrilly/lolcow
DEBUG   [U=1000,P=248639]  apiGet()                      apiGet calling v1/containers/mrcrilly/lolcow/lolcow.sif
DEBUG   [U=1000,P=248639]  apiGet()                      apiGet calling v1/images/mrcrilly/lolcow/lolcow.sif:sha256.5d8064dc526ecd5b666dc6de4e04b2118b116cbf41f24bbbfda3d66523d2fdb2?arch=amd64
DEBUG   [U=1000,P=248639]  postFileWrapper()             Now uploading to the library
DEBUG   [U=1000,P=248639]  postFileV2()                  Attempting to use multipart uploader
DEBUG   [U=1000,P=248639]  startMultipartUpload()        startMultipartUpload calling v2/imagefile/2/_multipart
DEBUG   [U=1000,P=248639]  apiCreate()                   apiCreate calling v2/imagefile/2/_multipart
DEBUG   [U=1000,P=248639]  postFileV2Multipart()         Multi-part upload: ID=[c2631c75-49f1-49cd-a42d-fe30568922e0] totalParts=[1] partSize=[94867456]
DEBUG   [U=1000,P=248639]  postFileV2Multipart()         Uploading part 1 (94867456 bytes)
0.0b / 90.5MiB [------------------------------------------------------------------------------] 0 % 0.0 b/s 0s
DEBUG   [U=1000,P=248639]  multipartUploadPart()         multipartUploadPart calling v2/imagefile/2/_multipart
0.0b / 90.5MiB [------------------------------------------------------------------------------] 0 % 0.0 b/s 0s
DEBUG   [U=1000,P=248639]  multipartUploadPart()         Failure uploading to presigned URL: Put "http://127.0.0.1:9000/sregistry/lolcow/lolcow.sif%3Asha256.5d8064dc526ecd5b666dc6de4e04b2118b116cbf41f24bbbfda3d66523d2fdb2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=newminio%2F20200705%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200705T212827Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host%3Bx-amz-content-sha256&partNumber=1&uploadId=c2631c75-49f1-49cd-a42d-fe30568922e0&X-Amz-Signature=95c17cd24b69be3f99d58c4dad4eb1fc1de173444b5d0e5f30670391a7956d30": dial tcp 127.0.0.1:9000: connect: connection refused
DEBUG   [U=1000,P=248639]  postFileV2Multipart()         Error uploading part 1: Put "http://127.0.0.1:9000/sregistry/lolcow/lolcow.sif%3Asha256.5d8064dc526ecd5b666dc6de4e04b2118b116cbf41f24bbbfda3d66523d2fdb2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=newminio%2F20200705%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200705T212827Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host%3Bx-amz-content-sha256&partNumber=1&uploadId=c2631c75-49f1-49cd-a42d-fe30568922e0&X-Amz-Signature=95c17cd24b69be3f99d58c4dad4eb1fc1de173444b5d0e5f30670391a7956d30": dial tcp 127.0.0.1:9000: connect: connection refused
DEBUG   [U=1000,P=248639]  abortMultipartUpload()        Aborting multipart upload ID: c2631c75-49f1-49cd-a42d-fe30568922e0
DEBUG   [U=1000,P=248639]  abortMultipartUpload()        abortMultipartUpload calling v2/imagefile/2/_multipart_abort
DEBUG   [U=1000,P=248639]  apiUpdate()                   apiUpdate calling v2/imagefile/2/_multipart_abort
DEBUG   [U=1000,P=248639]  postFileWrapper()             Upload completed OK
DEBUG   [U=1000,P=248639]  UploadImage()                 Setting tags against uploaded image
DEBUG   [U=1000,P=248639]  UploadImage()                 This library does not support multiple architectures per tag.
DEBUG   [U=1000,P=248639]  UploadImage()                 This tag will replace any already uploaded with the same name.
DEBUG   [U=1000,P=248639]  getTags()                     getTags calling v1/tags/1
DEBUG   [U=1000,P=248639]  setTags()                     Setting tag latest
DEBUG   [U=1000,P=248639]  setTag()                      setTag calling v1/tags/1
FATAL   [U=1000,P=248639]  func50()                      Unable to push image to library: creation did not succeed: http status code: 404
```

Perhaps this is important?

```
DEBUG   [U=1000,P=248639]  multipartUploadPart()         Failure uploading to presigned URL: Put "http://127.0.0.1:9000/sregistry/lolcow/lolcow.sif%3Asha256.5d8064dc526ecd5b666dc6de4e04b2118b116cbf41f24bbbfda3d66523d2fdb2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=newminio%2F20200705%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200705T212827Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host%3Bx-amz-content-sha256&partNumber=1&uploadId=c2631c75-49f1-49cd-a42d-fe30568922e0&X-Amz-
```

If you could shine some light on what I might be doing wrong that would be greatly appreciated. Thank you for the extensive amount of time you've committed to not only this project but assisting me with my problems.

---

My `config.py` file looks like this:

```
SECRET_KEY = 'some_secret'
ENABLE_GOOGLE_AUTH = False
ENABLE_TWITTER_AUTH = False
ENABLE_GITHUB_AUTH = False
ENABLE_BITBUCKET_AUTH = False
ENABLE_GITLAB_AUTH = True
SOCIAL_AUTH_GITLAB_SCOPE = ['read_user']
SOCIAL_AUTH_GITLAB_KEY = '<hidden>'
SOCIAL_AUTH_GITLAB_SECRET = '<hidden>''
DOMAIN_NAME = "https://<hidden>"
DOMAIN_NAME_HTTP = "https://<hidden>"
DOMAIN_NAKED = DOMAIN_NAME_HTTP.replace("https://", "")
ADMINS = (("<hidden>"),)
MANAGERS = ADMINS
HELP_CONTACT_EMAIL = "<hidden>"
HELP_INSTITUTION_SITE = "https://<hidden>"
REGISTRY_NAME = "Testing Repo"
REGISTRY_URI = "repo"
GOOGLE_ANALYTICS = None  # "UA-XXXXXXXXX"
DATA_UPLOAD_MAX_MEMORY_SIZE = None
USER_COLLECTIONS = True
USER_COLLECTION_LIMIT = 2
PRIVATE_ONLY = False
DEFAULT_PRIVATE = False
COLLECTIONS_VIEW_PAGE_COUNT = 250
CONTAINER_WEEKLY_GET_LIMIT = 100
COLLECTION_WEEKLY_GET_LIMIT = 100
DISABLE_BUILDING = False
SREGISTRY_GOOGLE_BUILD_LIMIT = 100
SREGISTRY_GOOGLE_BUILD_SINGULARITY_VERSION = "v3.3.0-slim"
SREGISTRY_GOOGLE_BUILD_TIMEOUT_SECONDS = None  # None defaults to 10 minutes
SREGISTRY_GOOGLE_BUILD_EXPIRE_SECONDS = 28800
CONTAINER_SIGNED_URL_EXPIRE_SECONDS = 10
DISABLE_GITHUB = False
DISABLE_BUILDING = False
DISABLE_BUILD_RECEIVE = False
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "postgres",
        "USER": "postgres",
        "HOST": "db",
        "PORT": "5432",
    }
}
LOGGING_SAVE_RESPONSES = True
VIEW_RATE_LIMIT = "50/1d"  # The rate limit for each view, django-ratelimit, "50 per day per ipaddress)
VIEW_RATE_LIMIT_BLOCK = (
    True  # Given that someone goes over, are they blocked for the period?
)
PLUGINS_ENABLED = [
    #    'pgp'
    #    'ldap_auth',
    #    'google_build'
    #    'pam_auth',
    #    'globus',
    #    'saml_auth'
]
MINIO_SERVER = "minio:9000"  # Internal to sregistry
MINIO_EXTERNAL_SERVER = (
    "127.0.0.1:9000"  # minio server for Singularity to interact with
)
MINIO_BUCKET = "sregistry"
MINIO_SSL = False  # use SSL for minio
MINIO_SIGNED_URL_EXPIRE_MINUTES = 5
MINIO_REGION = "us-east-1"
MINIO_MULTIPART_UPLOAD = True
```

The Nginx configuration looks like this:

```
server {
  listen                *:443 ssl default;
  server_name           <hidden>;

  ssl_certificate registry.crt;
  ssl_certificate_key registry.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers HIGH:!aNULL:!MD5;

  client_max_body_size 10024M;
  client_body_buffer_size 10024M;
  client_body_timeout 120;

  add_header X-Clacks-Overhead "GNU Terry Pratchett";
  add_header X-Clacks-Overhead "GNU Terry Pratchet";
  add_header Access-Control-Allow-Origin *;
  add_header 'Access-Control-Allow-Credentials' 'true';
  add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
  add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

  location /images {
    alias /var/www/images;
  }

  location ~* \.(php|aspx|myadmin|asp)$ {
    deny all;
  }

  location / {
    include /etc/nginx/uwsgi_params.par;
    uwsgi_pass uwsgi:3031;
    uwsgi_max_temp_file_size 10024m;
  }

  location /static {
    alias /var/www/static;
  }

  # Upload form should be submitted to this location
  location /upload {

        # Pass altered request body to this location
        upload_pass   /api/uploads/complete/;

        # Store files to this directory
        # The directory is hashed, subdirectories 0 1 2 3 4 5 6 7 8 9 should exist
        upload_store /var/www/images/_upload 1;        
        upload_store_access user:rw group:rw all:rw;

        # Set specified fields in request body
        upload_set_form_field $upload_field_name.name "$upload_file_name";
        upload_set_form_field $upload_field_name.content_type "$upload_content_type";
        upload_set_form_field $upload_field_name.path "$upload_tmp_path";

        # Inform backend about hash and size of a file
        upload_aggregate_form_field "$upload_field_name.md5" "$upload_file_md5";
        upload_aggregate_form_field "$upload_field_name.size" "$upload_file_size";

        upload_pass_form_field "^submit$|^description$";
        upload_pass_form_field "^SREGISTRY_EVENT$";
        upload_pass_form_field "^collection$";
        upload_pass_form_field "^name$";
        upload_pass_form_field "^tag$";
        upload_cleanup 400-599;

    }
}
```

Which I think you'll agree is standard minus the TLS configuration.

And finally my `docker-compose.yml` file:

```
db:
  image: postgres
  environment:
   - POSTGRES_HOST_AUTH_METHOD=trust

uwsgi:
  restart: always
  image: quay.io/vanessa/sregistry
  env_file:
    - ./.minio-env
  volumes:
    - .:/code
    - ./static:/var/www/static
    - ./images:/var/www/images
    # uncomment for PAM auth
    #- /etc/passwd:/etc/passwd 
    #- /etc/shadow:/etc/shadow
  links:
    - minio
    - redis
    - db

nginx:
  restart: always
  image: quay.io/vanessa/sregistry_nginx
  ports:
    - "443:443"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    - ./registry.crt:/etc/nginx/registry.crt
    - ./registry.key:/etc/nginx/registry.key
  volumes_from:
    - uwsgi
  links:
    - uwsgi
    - db

redis:
  restart: always
  image: redis:latest

scheduler:
  image: quay.io/vanessa/sregistry
  command: python /code/manage.py rqscheduler
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
  env_file:
    - ./.minio-env
  links:
    - minio
    - redis
    - db

worker:
  image: quay.io/vanessa/sregistry
  command: python /code/manage.py rqworker default
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
  env_file:
    - ./.minio-env
  links:
    - minio
    - redis
    - db

minio:
  image: minio/minio
  volumes:
    - ./minio-images:/images
  env_file:
   - ./.minio-env
  ports:
   - "9000:9000"  
  command: ["server", "images"]
```

**Comment by vsoch** [comment]
@mrcrilly the connection is being refused for Minio, which suggests some issue with its configuration. I’ve showed you how to debug Minio and tried to reproduce your issue twice now and I have not been able to - my pushes and pulls are successful. My offer stated previously still stands ☝️ https://github.com/singularityhub/sregistry/issues/305#issuecomment-652703852. I appreciate the details you’ve provided but if I cannot reproduce your error I cannot help you. Please consider following my suggestion to help developing a working ansible recipe to keep alongside the repository. If this is not appealing to you, best of luck.

**Comment by mrcrilly** [comment]
Is there anything about how I'm configuring Singularity Registry that stands out as odd or against convention?

Here is some additional information from MinIO:

```
[root@localhost sregistry]# ./mc admin trace -v myminio


minio [REQUEST s3.HeadBucket] 22:02:46.228
minio HEAD /sregistry/
minio Host: minio:9000
minio User-Agent: MinIO (Linux; x86_64) minio-py/5.0.8
minio X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
minio X-Amz-Date: 20200705T220246Z
minio Accept-Encoding: identity
minio Authorization: AWS4-HMAC-SHA256 Credential=newminio/20200705/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=e2ef5d75d283f8bb28b2a2e2b42670097965f486288f4157c09a19172e716d64
minio Content-Length: 0
minio 
minio [RESPONSE] [22:02:46.228] [ Duration 130µs  ↑ 93 B  ↓ 218 B ]
minio 200 OK
minio X-Amz-Request-Id: 161EFA5630C903A9
minio X-Xss-Protection: 1; mode=block
minio Accept-Ranges: bytes
minio Content-Length: 0
minio Content-Security-Policy: block-all-mixed-content
minio Server: MinIO/RELEASE.2020-06-22T03-12-50Z
minio Vary: Origin
minio 
minio 
minio [REQUEST s3.HeadBucket] 22:02:46.705
minio HEAD /sregistry/
minio Host: minio:9000
minio Accept-Encoding: identity
minio Authorization: AWS4-HMAC-SHA256 Credential=newminio/20200705/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=e2ef5d75d283f8bb28b2a2e2b42670097965f486288f4157c09a19172e716d64
minio Content-Length: 0
minio User-Agent: MinIO (Linux; x86_64) minio-py/5.0.8
minio X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
minio X-Amz-Date: 20200705T220246Z
minio 
minio [RESPONSE] [22:02:46.705] [ Duration 151µs  ↑ 93 B  ↓ 218 B ]
minio 200 OK
minio Accept-Ranges: bytes
minio Content-Length: 0
minio Content-Security-Policy: block-all-mixed-content
minio Server: MinIO/RELEASE.2020-06-22T03-12-50Z
minio Vary: Origin
minio X-Amz-Request-Id: 161EFA564D3E40FA
minio X-Xss-Protection: 1; mode=block
minio 
minio 
```

And...

```
minio [REQUEST s3.NewMultipartUpload] 22:06:28.487
minio POST /sregistry/lolcow/lolcow.sif:sha256.5d8064dc526ecd5b666dc6de4e04b2118b116cbf41f24bbbfda3d66523d2fdb2?uploads
minio Host: minio:9000
minio X-Amz-Date: 20200705T220628Z
minio Accept-Encoding: identity
minio Authorization: AWS4-HMAC-SHA256 Credential=newminio/20200705/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=3592f953a6eae09d62df4f013d1fa3b24f1d9698ae4fc38265bb7be0e5178a0d
minio Content-Length: 0
minio User-Agent: Boto3/1.14.14 Python/3.5.7 Linux/3.10.0-1127.el7.x86_64 Botocore/1.17.14
minio X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
minio 
minio [RESPONSE] [22:06:28.487] [ Duration 468µs  ↑ 93 B  ↓ 583 B ]
minio 200 OK
minio X-Xss-Protection: 1; mode=block
minio Accept-Ranges: bytes
minio Content-Length: 333
minio Content-Security-Policy: block-all-mixed-content
minio Content-Type: application/xml
minio Server: MinIO/RELEASE.2020-06-22T03-12-50Z
minio Vary: Origin
minio X-Amz-Request-Id: 161EFA89F0718169
minio <?xml version="1.0" encoding="UTF-8"?>
<InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>sregistry</Bucket><Key>lolcow/lolcow.sif:sha256.5d8064dc526ecd5b666dc6de4e04b2118b116cbf41f24bbbfda3d66523d2fdb2</Key><UploadId>a8663550-be47-483b-97bd-f4b9be9cacf6</UploadId></InitiateMultipartUploadResult>
minio 
```

**Comment by mrcrilly** [comment]
And I am willing to share this Ansible role once I have it working, but sadly following the documentation to the letter (even without my changes), does not yield a working result, so I am unsure how you're able to get it working.

It would be interesting to see the environment you're configuring and how you're configuring it. I'm obviously doing something wrong here and without extensive knowledge of the under laying systems it's actually quite hard to debug this, hence I am reliant on you.

I'm sorry I've been quite an inconvenience for you at this time. I finalise my work with my client tomorrow and although we've got a working solution in place it's now incredibly fragile as a result of everything breaking on your end. If I cannot resolve this then it simply leaves a lot of scientists in a fragile, unknown position using an older release of sregistry.

**Comment by mrcrilly** [comment]
Reopening for visibility from others.

**Comment by vsoch** [comment]
The point of doing a PR is so that I can reproduce your issue. It’s expected that the code would be be broken, but then I could explore and try to debug. I’m sorry your clients are disappointed but I’ve done everything that I can to help, and made suggestions for moving forward that are not appealing to you.
